name: lms
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  dio: ^5.3.3
  http: ^1.2.0
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  fl_chart: ^0.64.0
  video_player: ^2.8.1
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  youtube_player_flutter: ^8.1.2
  shimmer: ^3.0.0
  timeago: ^3.6.0
  flutter_quill: ^8.6.4
  uuid: ^4.2.1
  rxdart: ^0.27.7
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^16.2.0
  file_picker: ^6.1.1
  webview_flutter: ^4.4.4
  percent_indicator: ^4.2.3
  lottie: ^3.1.0
  syncfusion_flutter_charts: ^25.1.41+2
  url_launcher: ^6.2.6




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          style: normal

    - family: Kalpurush
      fonts:
        - asset: assets/fonts/kalpurush.ttf
          style: normal

    - family: Siyamrupali
      fonts:
        - asset: assets/fonts/Siyamrupali.ttf
          style: normal

    - family: Nikosh
      fonts:
        - asset: assets/fonts/Nikosh.ttf
          style: normal

    - family: SolaimanLipi
      fonts:
        - asset: assets/fonts/SolaimanLipi_20-04-07.ttf
          style: normal