name: lms
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  dio: ^5.3.3
#  go_router: ^12.0.0
#  http: ^1.1.0
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  fl_chart: ^0.64.0
  video_player: ^2.8.1
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  youtube_player_flutter: ^8.1.2
  shimmer: ^3.0.0
  timeago: ^3.6.0
  flutter_quill: ^8.6.4
  uuid: ^4.2.1
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  flutter_local_notifications: ^16.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/

